Q1.

package files;

public class payload {

//Declaring JSON in string for extracing the name w.r.t country 
public static String Players(String name, String country ) {
		String payload2= "{\r\n"
				+ "  \"name\": \"Royal Challengers Bangalore\",\r\n"
				+ "  \"location\": \"Bangalore\",\r\n"
				+ "  \"player\": [\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Batsman\",\r\n"
				+ "      \"price-in-crores\": \"7\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Batsman\",\r\n"
				+ "      \"price-in-crores\": \"15\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Batsman\",\r\n"
				+ "      \"price-in-crores\": \"11\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Bowler\",\r\n"
				+ "      \"price-in-crores\": \"7\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Bowler\",\r\n"
				+ "      \"price-in-crores\": \"10.75\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Bowler\",\r\n"
				+ "      \"price-in-crores\": \"10.75\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Wicket-keeper\",\r\n"
				+ "      \"price-in-crores\": \"5.5\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"All-Rounder\",\r\n"
				+ "      \"price-in-crores\": \"2.4\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Batsman\",\r\n"
				+ "      \"price-in-crores\": \"0.20\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Bowler\",\r\n"
				+ "      \"price-in-crores\": \"7.75\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \""+country+"\",\r\n"
				+ "      \"role\": \"Bowler\",\r\n"
				+ "      \"price-in-crores\": \"7.75\"\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}";
		return payload2;
		
	}
	
	//Declaring JSON in string for extracing the name w.r.t role
	public static String PlayersRole(String name, String role ) {
		String payload3= "{\r\n"
				+ "  \"name\": \"Royal Challengers Bangalore\",\r\n"
				+ "  \"location\": \"Bangalore\",\r\n"
				+ "  \"player\": [\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"South Africa\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"7\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"15\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"Australia\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"11\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"7\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"10.75\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"Srilanka\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"10.75\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"5.5\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"2.4\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"0.20\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"Australia\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"7.75\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"name\": \""+name+"\",\r\n"
				+ "      \"country\": \"India\",\r\n"
				+ "      \"role\": \""+role+"\",\r\n"
				+ "      \"price-in-crores\": \"7.75\"\r\n"
				+ "    }\r\n"
				+ "  ]\r\n"
				+ "}";
		return payload3;
		
	}
	
}